name: CI

on:
  pull_request:
  push:
    branches: [ master ]

permissions:
  contents: read

jobs:
  linter:
    name: Linter on a PR
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: Scalingo/actions/go-linter@main
        with:
          working-directory: support/kmsbp
  tests:
    name: Unit Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: Scalingo/actions/go-tests@main
        with:
          working-directory: support/kmsbp
